version: 2.1
jobs:
  deploy:
    docker:
      - image: google/cloud-sdk
        #auth:
        #  username: mydockerhub-user
        #  password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - add_ssh_keys:
          fingerprints:
              - "7f:fc:4e:fa:88:79:13:7a:c8:38:88:d0:e6:c8:bf:ff"
      # - run:
      #     name: Decrypt ssh key via env variable
      #     command: |
      #       echo $GCLOUD_SSH_KEY_PUB | base64 --decode --ignore-garbage > ${HOME}/.ssh/id_rsa_FINGER_PRINT_WITHOUT_COLONS.pub;
      #       chmod 0600 ${HOME}/.ssh/id_rsa_FINGER_PRINT_WITHOUT_COLONS.pub;
      - run: |
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          # sudo touch $HOME/.ssh/google_compute_engine
          # sudo echo $GCLOUD_SERVICE_KEY > $HOME/.ssh/google_compute_engine
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
          ## gcloud debug targets list --quiet
          ## List projects
          ## gcloud projects list --format="table(name, project_id, createTime.date(tz=LOCAL))"
          ## Run remote script
          ## gcloud beta compute ssh --zone "us-east1-d" "instance-1" --project "givebackhack-119"
          gcloud compute ssh instance-1 --command="echo 'hello world'" --quiet

workflows:
  test:
    jobs:
      - deploy