version: 2.1
jobs:
  deploy:
    docker:
      - image: google/cloud-sdk
        #auth:
        #  username: mydockerhub-user
        #  password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - run: |
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
          gcloud debug targets list --quiet
          ## List projects
          gcloud projects list --format="table(name, project_id, createTime.date(tz=LOCAL))"
          ## Run remote script
          gcloud compute ssh instance-1 --command=/home/deploy_staging.sh

workflows:
  install_and_configure_cli:
    jobs:
      - deploy
